name: Cypress tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    timeout-minute: 10
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2    
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npx @11ty/eleventy --serve
          spec: |
            cypress/integration/examples/axe.spec.js
