name: Cypress-Tests
on:
  push:
    branches: [ develop ]
    
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        spec: cypress/integration/axe.spec.js
