name: Cypress tests
on: [push]
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: opening-localhost
        with:
          start: npx @11ty/eleventy --serve
          wait-on: 'http://localhost:8080'
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          spec: |
            cypress/integration/examples/axe.spec.js
